require("plugins")
require("config")
require("ikonera.lsp")
require("ikonera.lspsaga")
require("ikonera.lualine")
require("ikonera.telescope")
require("ikonera.treesitter")
require("ikonera.nnn")
require("ikonera.trouble")
require("ikonera.gitsigns")
require("ikonera.prettier")
require("ikonera.notify")
require("ikonera.colorizer")
require("ikonera.comment")
require("pairs")
require("mappings")

