---
- name: Deploy all my dotfiles
  hosts: localhost
  vars_files:
    - ./values.yml

  tasks:
    - name: Set roles
      set_fact:
        roles: "{{ default_roles }}"

    - name: Run roles
      include_role:
        name: "{{ item }}"
      with_items: "{{ roles }}"
...
