---
linux_user: gabriel

kubectl:
  version: 1.23.0

neovim:
  version: nightly

alacritty:
  version: master

git:
  online:
    dir: "Lab/github.com"
  local:
    dir: "Lab"

lazygit:
  version: master

lazydocker:
  version: master

paru:
  version: master

tmux:
  version: master

spaceship:
  version: master
