---
- name: Install
  ansible.builtin.package:
    name: lazygit
    state: latest
  become: true

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/lazygit"
    state: "directory"

- name: Copy config files
  ansible.builtin.copy:
    src: "config.yml"
    dest: "{{ ansible_user_dir }}/.config/lazygit"
...
