---
- name: Uninstall nodejs first
  ansible.builtin.package:
    name:
      - node-gyp
      - nodejs-nopt
      - npm
      - semver
      - nodejs
    state: absent
  become: true

- name: Core
  ansible.builtin.package:
    name: "nodejs-lts-gallium"
    state: latest
  become: true

- name: Yarn
  ansible.builtin.package:
    name: yarn
    state: latest
  become: true

- name: Npm
  ansible.builtin.package:
    name: npm
    state: latest
  become: true
...
