---
- name: Verify node installation
  ansible.builtin.stat:
    path: "/usr/bin/node"
  register: node_install

- name: Verify yarn installation
  ansible.builtin.stat:
    path: "/usr/bin/node"
  register: yarn_install

- name: Uninstall nodejs first
  ansible.builtin.package:
    name:
      - node-gyp
      - nodejs-nopt
      - npm
      - semver
      - nodejs
    state: absent
  become: true
  when: not node_install.stat.exists

- name: Core
  ansible.builtin.package:
    name: "nodejs-lts-gallium"
    state: latest
  become: true
  when: not node_install.stat.exists

- name: Yarn
  ansible.builtin.package:
    name: yarn
    state: latest
  become: true
  when: not yarn_install.stat.exists

- name: Npm
  ansible.builtin.package:
    name: npm
    state: latest
  become: true
  when: not node_install.stat.exists
...
