---
- name: Install
  ansible.builtin.package:
    name: zsh
    state: latest
  become: true

- name: Copy setup file
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir/.zshrc }}"

- name: Change default user shell prompt
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    shell: "/usr/bin/zsh"
  become: true
...
