---
- name: Create config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/picom"
    state: "directory"

- name: Copy config file
  ansible.builtin.copy:
    src: "picom.conf"
    dest: "{{ ansible_user_dir }}/.config/picom/picom.conf"
...
