---
- name: Verify installation
  ansible.builtin.stat:
    path: "/usr/bin/paru"
  register: install

- name: Clone paru from github
  ansible.builtin.git:
    depth: 1
    single_branch: yes
    repo: "https://github.com/Morganamilo/paru.git"
    dest: "{{ ansible_user_dir }}/{{ git.online.dir }}/paru"
    update: yes
    clone: yes
    force: yes
    version: "{{ paru.version }}"

- name: Build it
  ansible.builtin.shell:
    chdir: "{{ ansible_user_dir }}/{{ git.online.dir }}/paru"
    cmd: "source $HOME/.cargo/env; cargo build --release"

- name: Delete previous version
  ansible.builtin.file:
    path: "/usr/bin/paru"
    state: "absent"
  become: true
  when: install.stat.exists

- name: Move to binaries
  ansible.builtin.shell:
    chdir: "{{ ansible_user_dir }}/{{ git.online.dir }}/paru"
    cmd: "cp target/release/paru /usr/bin/paru"
  become: true
