---
- name: Verify installation
  ansible.builtin.stat:
    path: "/usr/bin/paru"
  register: install

- name: Clone paru from github
  ansible.builtin.git:
    depth: 1
    single_branch: yes
    repo: "https://github.com/Morganamilo/paru.git"
    dest: "{{ ansible_user_dir }}/{{ git.online.dir }}/paru"
    update: yes
    clone: yes
    force: yes
    version: "{{ paru.version }}"

- name: Build it
  ansible.builtin.shell:
    chdir: "{{ ansible_user_dir }}/{{ git.online.dir }}/paru"
    cmd: "makepkg -si"
