---
- name: Import gpg key
  ansible.builtin.command:
    cmd: curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | gpg --import -

- name: Install
  kewlfft.aur.aur:
    name: spotify
    state: latest
...
