---
- name: Import gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg

- name: Install
  kewlfft.aur.aur:
    name: spotify
    state: latest
...
