---
# don't need installation step in case of applying onto a system that already have i3-gaps installed.
- name: Copy config file
  ansible.builtin.copy:
    src: "config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    mode: "0755"
...
