---
- name: Verify installation
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/rofi"
  register: conf_dir

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    dest: "{{ ansible_user_dir }}/.config/rofi"
    state: "directory"
  when: conf_dir.stat.isdir is not defined

- name: Copy config file
  ansible.builtin.copy:
    mode: "0755"
    src: "config.rasi"
    dest: "{{ ansible_user_dir }}/.config/rofi/config.rasi"

- name: Copy theme file
  ansible.builtin.copy:
    mode: "0755"
    src: "themes"
    dest: "{{ ansible_user_dir }}/.config/rofi"

- name: Install rofi
  ansible.builtin.package:
    name: rofi
    state: latest
  become: true
