---
- name: Download installer
  ansible.builtin.get_url:
    mode: "0755"
    dest: "/tmp/omz-installer.sh"
    url: "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

- name: Run installer
  ansible.builtin.shell:
    cmd: "/tmp/omz-installer.sh"

- name: Remove omz installer
  file:
    path: "/tmp/omz-install.sh"
    state: "absent"

- name: Copy config file
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
...
