---
- name: Core
  ansible.builtin.package:
    name: docker
    state: latest
  become: true

- name: Compose
  ansible.builtin.package:
    name: docker-compose
    state: latest
  become: true
...
