---
- name: Install
  kewlfft.aur.aur:
    use: yay
    name: insomnia
    state: latest
  become: true

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/Insomnia/plugins"
    state: "directory"

- name: Copy theme file
  ansible.builtin.copy:
    src: "insomnia-plugin-theme-tokyo-night"
    dest: "{{ ansible_user_dir }}/.config/Insomnia/plugins"

...
