---
- name: Verify installation
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/alacritty"
  register: install

- name: Verify previous version
  ansible.builtin.stat:
    path: "/usr/bin/alacritty"
  register: previous

- name: Install dependencies
  ansible.builtin.package:
    name:
      - cmake
      - freetype2
      - fontconfig
      - pkg-config
      - make
      - libxcb
      - libxkbcommon
      - python
    state: latest
  become: true
  when: not install.stat.exists

- name: Clone alacritty from github
  ansible.builtin.git:
    depth: 1
    dest: "{{ ansible_user_dir }}/{{ git.online.dir }}/alacritty"
    force: yes
    repo: https://github.com/alacritty/alacritty.git
    version: "{{ alacritty.version }}"
    update: yes
    clone: yes

- name: Build alacritty
  ansible.builtin.shell:
    chdir: "{{ ansible_user_dir }}/{{ git.online.dir }}/alacritty"
    cmd: "source $HOME/.cargo/env; cargo build --release"

- name: If already exists, remove it
  ansible.builtin.shell:
    cmd: "rm /usr/bin/alacritty"
  become: true
  when: previous.stat.exists

- name: Move to binaries
  ansible.builtin.shell:
    chdir: "{{ ansible_user_dir }}/{{ git.online.dir }}/alacritty"
    cmd: "cp target/release/alacritty /usr/bin/alacritty"
  become: true

- name: Create config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: "directory"
  when: not install.stat.exists

- name: Copy theme file
  ansible.builtin.copy:
    src: "tokyonight-alacritty.yml"
    dest: "{{ ansible_user_dir }}/.config/alacritty"

- name: Copy config file
  ansible.builtin.copy:
    src: "alacritty.yml"
    dest: "{{ ansible_user_dir }}/.config/alacritty"
...

