---
- name: Verify installation
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/spaceship"
  register: install

- name: Install spaceship
  ansible.builtin.git:
    depth: 1
    clone: yes
    force: yes
    update: yes
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "{{ ansible_user_dir }}/.zsh/themes/spaceship"
    version: "{{ spaceship.version }}"

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/spaceship"
    state: "directory"
  when: not install.stat.exists

- name: Copy config file
  ansible.builtin.copy:
    src: "spaceship.zsh"
    dest: "{{ ansible_user_dir }}/.config/spaceship/spaceship.zsh"
