---
- name: Verify installation
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/Lab/github.com/neovim"
  register: install

- name: Clone nightly version from github
  ansible.builtin.git:
    depth: 1
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ ansible_user_dir }}/Lab/github.com/neovim"
    single_branch: yes
    version: "nightly"
    clone: yes
    update: yes
  register: clone

- name: Install deps
  community.general.make:
    chdir: "{{ ansible_user_dir }}/Lab/github.com/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  become: true

- name: Install neovim
  community.general.make:
    chdir: "{{ ansible_user_dir }}/Lab/github.com/neovim"
    target: install
  become: true

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: "directory"
  when: not install.stat.exists

- name: Copy init.lua
  ansible.builtin.copy:
    src: "init.lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/"

- name: Copy lua folder
  ansible.builtin.copy:
    src: "lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/"
...

