---
- name: Install
  ansible.builtin.package:
    name: neovim
    state: latest
  become: true

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: "directory"

- name: Copy init.lua
  ansible.builtin.copy:
    src: "init.lua"
    dest: "{{ ansible_user_dir }}/.config/nvim"

- name: Copy lua folder
  ansible.builtin.copy:
    src: "lua"
    dest: "{{ ansible_user_dir }}/.config/nvim"
...

