---
- name: Verify installation
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/{{ git.online.dir }}/neovim"
  register: install

- name: Install deps
  ansible.builtin.package:
    name:
      - base-devel
      - cmake
      - unzip
      - ninja
      - tree-sitter
      - curl
    state: latest
  become: true
  when: not install.stat.exists

- name: Clone nightly version from github
  ansible.builtin.git:
    depth: 1
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ ansible_user_dir }}/{{ git.online.dir }}/neovim"
    single_branch: yes
    version: "{{ neovim.version }}"
    clone: yes
    update: yes
  register: clone

- name: Build it
  community.general.make:
    chdir: "{{ ansible_user_dir }}/{{ git.online.dir }}/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  become: true

- name: Install neovim
  community.general.make:
    chdir: "{{ ansible_user_dir }}/{{ git.online.dir }}/neovim"
    target: install
  become: true

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: "directory"
  when: not install.stat.exists

- name: Copy init.lua
  ansible.builtin.copy:
    src: "nvim-config/init.lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/"

- name: Copy lua folder
  ansible.builtin.copy:
    src: "nvim-config/lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/"
---
